Repository rjstrong0101/Group-6-Team-Project, pull requests merged in 2020-11, with the labels that each got.

#53 Sql crud ops part 2
  .gitignore
  pom.xml
  src/main/java/QueryMaker.java
  src/main/java/Transaction.java
Labels: enhancement

#54 a few changes for appearence & added some input check for search button
  .idea/compiler.xml
  .idea/workspace.xml
  src/main/java/CupOJavaGui.java
Labels: help wanted

#55 QueryMaker.java Documentation
  src/main/java/QueryMaker.java
Labels: documentation

#57 Resolved database security breach, modified gitignore file
  .gitignore
  src/main/java/Credentials.java
  src/main/java/CupOJavaGui.java
  src/main/java/MailService.java
  src/main/java/Main.java
  src/main/java/QueryMaker.java
  src/main/java/QueryMakerTest.java
Labels: enhancement

#58 Email orders to database
  .gitignore
  src/main/java/Credentials.java
  src/main/java/MailService.java
  src/main/java/Main.java
  src/main/java/QueryMaker.java
Labels: enhancement

#60 Database redesign
  pom.xml
  src/main/java/Credentials.java
  src/main/java/MailService.java
  src/main/java/Main.java
  src/main/java/QueryMaker.java
  src/main/java/TimeSeriesCreate.java
  src/main/java/Transaction.java
Labels: enhancement

#61 daily assets functionality included
  src/main/java/Main.java
  src/main/java/QueryMaker.java
Labels: enhancement

#62 Added implimention for recieving cancellation emails
  src/main/java/MailService.java
  src/main/java/QueryMaker.java
  src/main/java/Transaction.java
Labels: enhancement

#63 SQL - Mail and Analytics
  src/main/java/Credentials.java
  src/main/java/Main.java
  src/main/java/QueryMaker.java
  src/main/java/TimeSeries_AWT.java
  src/main/java/Transaction.java
Labels: enhancement
