Repository rjstrong0101/Group-6-Team-Project, pull requests merged in 2020-12, with the labels that each got.

#64 Performed code cleanup and eliminated unused classes
  src/main/java/Credentials.java
  src/main/java/Inventory.java
  src/main/java/MailService.java
  src/main/java/Product.java
  src/main/java/QueryMaker.java
  src/main/java/Transaction.java
Labels: documentation

#66 Mailservice date fix
  src/main/java/MailService.java
  src/main/java/QueryMaker.java
Labels: bug

#67 more cleanup & JUnit fix
  customer_orders_final_team6.csv
  src/main/java/Credentials.java
  src/main/java/CupOJavaGui.java
  src/main/java/MailService.java
  src/main/java/Main.java
  src/main/java/QueryMaker.java
  src/main/java/QueryMakerTest.java
  src/main/java/TimeSeriesCreate.java
  src/main/java/TimeSeries_AWT.java
  src/main/java/Transaction.java
Labels: bug, documentation

#68 minor optimization & user story 5 addition
  Team_6.iml
  src/main/java/Main.java
  src/main/java/QueryMaker.java
  src/main/java/TimeSeries_AWT.java
Labels: enhancement

#69 uploading sql stored procedures
  sql_snippets/DatabaseAfterCreation.PNG
  sql_snippets/batchLoading.sql
  sql_snippets/createDB_Structure.sql
  sql_snippets/create_dimdate.sql
  sql_snippets/daily_assets.sql
  sql_snippets/daily_orders.sql
  sql_snippets/daily_purchases.sql
  sql_snippets/emailAssetAddition.sql
  sql_snippets/emailLoading.sql
  sql_snippets/generateDailyAssets.sql
  sql_snippets/specificDailyAssets.sql
  sql_snippets/topTenCustomers.sql
  sql_snippets/topTenProducts.sql
Labels: documentation, enhancement
