Repository rjstrong0101/Group-6-Team-Project, pull requests merged in 2020-10, with the labels that each got.

#42 Riley mail service
  .gitignore
  src/main/java/MailService.java
Labels: enhancement

#43 created a GUI for future ease of presentation
  src/main/java/CupOJavaGui.java
Labels: help wanted

#44 file cleanup - deleting csv from testing runs
  LOOKOVERHERE.csv
  TESTFILE.csv
Labels: wontfix

#46 Revert "Gui hot fix"
  src/main/java/CupOJavaGui.java
  src/main/java/QueryMaker.java
Labels: bug

#48 round two documenation
  src/main/java/Credentials.java
  src/main/java/Inventory.java
  src/main/java/MailService.java
  src/main/java/Product.java
  src/main/java/Transaction.java
Labels: documentation

#49 Added timerseries plot without our data
  src/main/java/TimeSeriesCreate.java
Labels: enhancement

#50 unnecessary java file deletion & dependency addition
  pom.xml
  src/main/java/CustomerTable.java
Labels: documentation

#51 adds test methods
  src/main/java/QueryMakerTest.java
Labels: enhancement

#52 Modified GUI to work properly
  src/main/java/CupOJavaGui.java
  src/main/java/QueryMaker.java
Labels: enhancement
